# Generated by Django 3.0 on 2020-02-29 18:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('numAcheteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nomAcheteur', models.CharField(max_length=30)),
                ('prenomAcheteur', models.CharField(max_length=30)),
                ('mailAcheteur', models.EmailField(max_length=254)),
                ('noteAcheteur', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('adresseAcheteur', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('numVendeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nomVendeur', models.CharField(max_length=30)),
                ('prenomVendeur', models.CharField(max_length=30)),
                ('mailVendeur', models.EmailField(max_length=254)),
                ('noteVendeur', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'vendeur',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('numProduit', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/%D/%m/%Y/')),
                ('prixBase', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dateDebut', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de début de l'enchère")),
                ('dateFin', models.DateTimeField(verbose_name="Date de fin de l'enchère")),
                ('categorie', models.CharField(choices=[('Emploi', 'Véhicules'), ('Vacances', 'Loisirs'), ('Mode', 'Multimédia'), ('Maison', 'Autre')], max_length=30)),
                ('vendeurFK', models.ForeignKey(db_column='numVendeur', on_delete=django.db.models.deletion.CASCADE, to='PT.Vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='Enchere',
            fields=[
                ('numEnchere', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('commentaire', models.CharField(max_length=50)),
                ('acheteurFK', models.ForeignKey(db_column='numAcheteur', on_delete=django.db.models.deletion.CASCADE, to='PT.Acheteur')),
                ('produitFK', models.ForeignKey(db_column='numProduit', on_delete=django.db.models.deletion.CASCADE, to='PT.Produit')),
            ],
            options={
                'db_table': 'Enchere',
            },
        ),
    ]
