# Generated by Django 3.0 on 2020-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='photoVendeur',
            field=models.ImageField(default='default.jpg', upload_to='photosdeprofil'),
        ),
    ]
