# Generated by Django 3.0 on 2020-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0002_vendeur_photovendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='photoVendeur',
            field=models.ImageField(default='default.png', upload_to='photosdeprofil'),
        ),
    ]
