# Generated by Django 3.0 on 2020-03-03 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0003_auto_20200302_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='totalEnchere',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
