# Generated by Django 3.0 on 2020-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0004_produit_totalenchere'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheteur',
            name='photoAcheteur',
            field=models.ImageField(default='default.png', upload_to='photosdeprofil'),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='adresseAcheteur',
            field=models.TextField(null=True),
        ),
    ]
