# Generated by Django 3.0 on 2020-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0005_auto_20200305_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheteur',
            name='noteAcheteur',
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('Emploi', 'Emploi'), ('Véhicules', 'Véhicules'), ('Vacances', 'Vacances'), ('Loisirs', 'Loisirs'), ('Mode', 'Mode'), ('Multimédia', 'Multimédia'), ('Maison', 'Maison'), ('Autre', 'Autre')], max_length=30),
        ),
    ]
