# Generated by Django 3.0 on 2020-03-05 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0006_auto_20200305_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='noteVendeur',
        ),
        migrations.AlterField(
            model_name='enchere',
            name='commentaire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enchere',
            name='montant',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name="Montant de l'enchère"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(verbose_name='Description du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixBase',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mise à prix'),
        ),
    ]
