# Generated by Django 3.0 on 2020-03-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0007_auto_20200305_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='enchere',
            name='moment',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
