# Generated by Django 3.0 on 2020-03-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0008_enchere_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='acheteurFK',
            field=models.ForeignKey(blank=True, db_column='acheteurFK', null=True, on_delete=django.db.models.deletion.CASCADE, to='PT.Acheteur'),
        ),
        migrations.AlterField(
            model_name='enchere',
            name='moment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
